version: "3.8"
services:
  database:
    container_name: database
    image: mongo:4.4
    ports:
      - 27017:27017
    command: mongod
    restart: unless-stopped

  backend:
    container_name: backend
    build: backend/
    image: backend
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file:
      - backend/.env
    restart: unless-stopped
  
  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    links:
      - backend
    env_file:
      - frontend/.env
    restart: unless-stopped


    
